### ISSUE TITLE
Change sequence of properties in core:AbstractSpaceType

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0Encodings#22]
The `boundary` property element of `core:AbstractSpaceType` is currently defined to be encoded after the LOD 0-2 geometry properties of the space but before its LOD 3 geometry properties. Either it should be defined before all geometry properties or after them (my preferred solution), but not inbetween.

**Comment by TatjanaKutzner** [comment]
I defined the sequence in this way to follow the sequence in CityGML 2.0. When you look at the `bldg:AbstractBuildingType` in CityGML 2.0, then the `boundedBy` property element is encoded after the LOD 0-2 and before the LOD3-4 geometry properties.

I don't know if this was done on purpose. But in general it would definitely make more sense to define the `boundary` element after the geometry properties.

**Comment by clausnagel** [comment]
I see. Well I don’t think there was a specific reason to do it this way in CityGML 2.0. So I would also be happy to change it.

Also note that for other types the sequence is completely different than in CotyGML 2.0. Take ImplicitGeometryType for example.

**Comment by TatjanaKutzner** [comment]
I think we have to define the `boundary` property before all geometry properties. 

When defining the `boundary` property after the last geometry property of `AbstractSpace`, objects that are subclasses of `AbstractPhysicalSpace` will still have the `boundary` property before the `lod1/2/3TerrainIntersectionCurve` geometries in GML instance documents. 
The reason is that the `lod1/2/3errainIntersectionCurve` geometries are defined for `AbstractPhysicalSpace`; thus, first the properties of `AbstractSpace` have to appear in instance documents, followed by the properties from the subclasses.

**Comment by clausnagel** [comment]
We discussed this issue in the GML encoding subgroup meeting on May 21, 2021 and agreed that the order as proposed and implemented by Tatjana is our preferred one. One more reason to support this order is that we want to use XLinks from the space geometry to the geometries of the space boundaries. So, it makes sense that the geometries of the space boundaries come first in a dataset.
